import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  FileText,
  Footprints,
  GraduationCap,
  Home,
  Layers,
  LayoutGrid,
  Mail,
  Map,
  Newspaper,
  Sparkles,
  UserCircle,
  MessageSquare,
} from "lucide-react";
import {
  HOME_API_PATH,
  HOME_CMS_FORM_FIELDS,
  HOME_SECTIONS_API_PATH,
  HOME_SECTIONS_FORM_FIELDS,
} from "@/app/frontend/CMS/config/home-cms-fields";

import type { FormField } from "@/app/frontend/CMS/config/cms-field-types";

export type { FieldType, FormField } from "@/app/frontend/CMS/config/cms-field-types";

export type CmsModuleConfig = {
  slug: string;
  apiPath: string;
  label: string;
  group: string;
  icon?: LucideIcon;
  hasStatus?: boolean;
  /** PATCH path segment for status toggle (default `status`) */
  statusPath?: string;
  /** Body field for status toggle (default `status`; fields API uses `isVisible`) */
  statusField?: "status" | "isVisible";
  singleRecord?: boolean;
  formFields?: FormField[];
};

/** Home hero + blocks (single document) */
export const HOME_CMS_MODULE: CmsModuleConfig = {
  slug: "home",
  apiPath: HOME_API_PATH,
  label: "Home CMS",
  group: "home",
  icon: Home,
  singleRecord: true,
  formFields: HOME_CMS_FORM_FIELDS,
};

/** Courses listing page CMS (single document) — `/courses` */
export const COURSES_PAGE_FORM_FIELDS: FormField[] = [
  { key: "headerText", label: "Header Text", type: "text" },
  { key: "title", label: "Title", type: "text" },
  { key: "subtitle", label: "Subtitle", type: "textarea" },
  { key: "emptyStateText", label: "Empty State Text", type: "text" },
  { key: "isVisible", label: "Visible", type: "boolean" },
];

export const COURSES_PAGE_MODULE: CmsModuleConfig = {
  slug: "courses-page",
  apiPath: "/courses",
  label: "Course CMS",
  group: "frontend",
  icon: LayoutGrid,
  singleRecord: true,
  formFields: COURSES_PAGE_FORM_FIELDS,
};

/** Home page sections (single document) */
export const HOME_SECTIONS_MODULE: CmsModuleConfig = {
  slug: "home-sections",
  apiPath: HOME_SECTIONS_API_PATH,
  label: "Home Sections",
  group: "section",
  icon: Layers,
  singleRecord: true,
  formFields: HOME_SECTIONS_FORM_FIELDS,
};

export const CMS_MODULES: CmsModuleConfig[] = [
  {
    slug: "about",
    apiPath: "/pages/about",
    label: "About Page",
    group: "cms",
    icon: FileText,
    singleRecord: true,
    formFields: [
      { key: "headerText", label: "Header Text", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "contact",
    apiPath: "/pages/contact",
    label: "Contact Page",
    group: "cms",
    icon: Mail,
    singleRecord: true,
    formFields: [
      { key: "headerText", label: "Header Text", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "login-page",
    apiPath: "/login",
    label: "Login Page (CMS)",
    group: "cms",
    icon: FileText,
    singleRecord: true,
    formFields: [
      { key: "headerText", label: "Header Text", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "submitButton.label", label: "Submit Button Label", type: "text" },
      { key: "submitButton.url", label: "Submit Button URL", type: "text" },
      { key: "submitButton.isVisible", label: "Submit Button Visible", type: "boolean" },
      { key: "registerLink.label", label: "Register Link Label", type: "text" },
      { key: "registerLink.url", label: "Register Link URL", type: "text" },
      { key: "registerLink.isVisible", label: "Register Link Visible", type: "boolean" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "register-page",
    apiPath: "/register",
    label: "Register Page (CMS)",
    group: "cms",
    icon: FileText,
    singleRecord: true,
    formFields: [
      { key: "headerText", label: "Header Text", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "submitButton.label", label: "Submit Button Label", type: "text" },
      { key: "submitButton.url", label: "Submit Button URL", type: "text" },
      { key: "submitButton.isVisible", label: "Submit Button Visible", type: "boolean" },
      { key: "loginLink.label", label: "Login Link Label", type: "text" },
      { key: "loginLink.url", label: "Login Link URL", type: "text" },
      { key: "loginLink.isVisible", label: "Login Link Visible", type: "boolean" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "footer",
    apiPath: "/footer",
    label: "Footer",
    group: "cms",
    icon: Footprints,
    singleRecord: true,
    formFields: [
      { key: "tagline", label: "Tagline", type: "textarea" },
      { key: "platformLinks", label: "Platform Links", type: "linkList" },
      { key: "learningLinks", label: "Learning Links", type: "linkList" },
      { key: "companyLinks", label: "Company Links", type: "linkList" },
      { key: "supportLinks", label: "Support Links", type: "linkList" },
      { key: "socialLinks", label: "Social Links", type: "linkList" },
      { key: "paymentMethods", label: "Payment Methods", type: "paymentList" },
      { key: "copyrightText", label: "Copyright Text", type: "text" },
      { key: "privacyLink.label", label: "Privacy Link Label", type: "text" },
      { key: "privacyLink.url", label: "Privacy Link URL", type: "text" },
      { key: "privacyLink.isVisible", label: "Privacy Link Visible", type: "boolean" },
      { key: "termsLink.label", label: "Terms Link Label", type: "text" },
      { key: "termsLink.url", label: "Terms Link URL", type: "text" },
      { key: "termsLink.isVisible", label: "Terms Link Visible", type: "boolean" },
      { key: "sitemapLink.label", label: "Sitemap Link Label", type: "text" },
      { key: "sitemapLink.url", label: "Sitemap Link URL", type: "text" },
      { key: "sitemapLink.isVisible", label: "Sitemap Link Visible", type: "boolean" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "courses-page",
    apiPath: "/courses",
    label: "Courses Page",
    group: "cms",
    icon: LayoutGrid,
    singleRecord: true,
    formFields: COURSES_PAGE_FORM_FIELDS,
  },
  {
    slug: "roadmaps-page",
    apiPath: "/roadmaps",
    label: "Roadmaps Page",
    group: "cms",
    icon: Map,
    singleRecord: true,
    formFields: [
      { key: "headerText", label: "Header Text", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "emptyStateText", label: "Empty State Text", type: "text" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "scholarships-page",
    apiPath: "/scholarships",
    label: "Scholarships Page",
    group: "cms",
    icon: GraduationCap,
    singleRecord: true,
    formFields: [
      { key: "headerText", label: "Header Text", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "emptyStateText", label: "Empty State Text", type: "text" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "blog-page",
    apiPath: "/blog",
    label: "Blog Page",
    group: "cms",
    icon: Newspaper,
    singleRecord: true,
    formFields: [
      { key: "headerText", label: "Header Text", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "textarea" },
      { key: "emptyStateText", label: "Empty State Text", type: "text" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "fields",
    apiPath: "/fields",
    label: "Fields",
    group: "section",
    icon: Layers,
    hasStatus: true,
    statusPath: "updateStatus",
    statusField: "isVisible",
    formFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "icon", label: "Icon", type: "text" },
      { key: "sortOrder", label: "Sort Order", type: "number" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "why-yaclam",
    apiPath: "/why_yaclam",
    label: "Why Yaclam",
    group: "section",
    icon: Sparkles,
    hasStatus: false,
    formFields: [
      { key: "icon", label: "Icon", type: "text" },
      { key: "title", label: "Title", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea", required: true },
      { key: "sortOrder", label: "Sort Order", type: "number" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "practitioners",
    apiPath: "/practitioners",
    label: "Practitioners",
    group: "section",
    icon: UserCircle,
    hasStatus: false,
    formFields: [
      { key: "initials", label: "Initials", type: "text" },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "role", label: "Role", type: "text" },
      { key: "coursesCount", label: "Courses Count", type: "number" },
      { key: "studentsCount", label: "Students Count", type: "text" },
      { key: "color", label: "Color", type: "text" },
      { key: "sortOrder", label: "Sort Order", type: "number" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "testimonials",
    apiPath: "/testimonials",
    label: "Testimonials",
    group: "section",
    icon: MessageSquare,
    hasStatus: false,
    formFields: [
      { key: "description", label: "Description", type: "textarea", required: true },
      { key: "profileImage", label: "Profile Image URL", type: "text" },
      { key: "initials", label: "Initials", type: "text" },
      { key: "name", label: "Name", type: "text", required: true },
      { key: "role", label: "Role", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "sortOrder", label: "Sort Order", type: "number" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
  {
    slug: "course",
    apiPath: "/course",
    label: "Courses",
    group: "course",
    icon: BookOpen,
    hasStatus: true,
    formFields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "fieldId", label: "Field (ObjectId)", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "shortDescription", label: "Short Description", type: "textarea" },
      { key: "category", label: "Category", type: "text" },
      { key: "level", label: "Level", type: "text" },
      { key: "duration", label: "Duration", type: "text" },
      { key: "instructorName", label: "Instructor", type: "text" },
      { key: "thumbnail", label: "Thumbnail URL", type: "text" },
      { key: "price", label: "Price", type: "number" },
      { key: "originalPrice", label: "Original Price", type: "number" },
      { key: "isFree", label: "Free", type: "boolean" },
      { key: "isFeatured", label: "Featured", type: "boolean" },
      { key: "isPublished", label: "Published", type: "boolean" },
      { key: "isVisible", label: "Visible", type: "boolean" },
      { key: "durationHours", label: "Duration Hours", type: "number" },
      { key: "lessonCount", label: "Lesson Count", type: "number" },
      { key: "rating", label: "Rating", type: "number" },
      { key: "reviewCount", label: "Review Count", type: "number" },
      { key: "studentCount", label: "Student Count", type: "number" },
      { key: "sortOrder", label: "Sort Order", type: "number" },
      { key: "badges.premium.text", label: "Premium Badge Text", type: "text" },
      { key: "badges.premium.isVisible", label: "Premium Badge Visible", type: "boolean" },
      { key: "badges.free.text", label: "Free Badge Text", type: "text" },
      { key: "badges.free.isVisible", label: "Free Badge Visible", type: "boolean" },
      { key: "ctaButton.label", label: "CTA Button Label", type: "text" },
      { key: "ctaButton.url", label: "CTA Button URL", type: "text" },
      { key: "ctaButton.style", label: "CTA Button Style", type: "text" },
      { key: "ctaButton.isVisible", label: "CTA Button Visible", type: "boolean" },
      { key: "wishlistButton.isVisible", label: "Wishlist Visible", type: "boolean" },
      { key: "status", label: "Status", type: "boolean" },
    ],
  },
  {
    slug: "roadmap",
    apiPath: "/roadmap",
    label: "Roadmaps",
    group: "course",
    icon: Map,
    hasStatus: true,
    formFields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "icon", label: "Icon", type: "text" },
      { key: "skills", label: "Skills (comma separated)", type: "stringList" },
      { key: "steps", label: "Steps", type: "stepsList" },
      { key: "ctaButton.label", label: "CTA Button Label", type: "text" },
      { key: "ctaButton.url", label: "CTA Button URL", type: "text" },
      { key: "ctaButton.isVisible", label: "CTA Button Visible", type: "boolean" },
      { key: "isPublished", label: "Published", type: "boolean" },
      { key: "isVisible", label: "Visible", type: "boolean" },
      { key: "sortOrder", label: "Sort Order", type: "number" },
      { key: "status", label: "Status", type: "boolean" },
    ],
  },
  {
    slug: "scholarship",
    apiPath: "/scholarship",
    label: "Scholarships",
    group: "course",
    icon: GraduationCap,
    hasStatus: true,
    formFields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "title", label: "Title", type: "text" },
      { key: "provider", label: "Provider", type: "text" },
      { key: "country", label: "Country", type: "text" },
      { key: "level", label: "Level", type: "text" },
      { key: "funding", label: "Funding", type: "text" },
      { key: "flag", label: "Flag", type: "text" },
      { key: "amount", label: "Amount", type: "text" },
      { key: "deadline", label: "Deadline", type: "text" },
      { key: "eligibility", label: "Eligibility", type: "textarea" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "applicationUrl", label: "Application URL", type: "text" },
      { key: "ctaButton.label", label: "CTA Button Label", type: "text" },
      { key: "ctaButton.url", label: "CTA Button URL", type: "text" },
      { key: "ctaButton.isVisible", label: "CTA Button Visible", type: "boolean" },
      { key: "isFeatured", label: "Featured", type: "boolean" },
      { key: "isPublished", label: "Published", type: "boolean" },
      { key: "isVisible", label: "Visible", type: "boolean" },
      { key: "sortOrder", label: "Sort Order", type: "number" },
      { key: "status", label: "Status", type: "boolean" },
    ],
  },
  {
    slug: "blog-post",
    apiPath: "/blog_post",
    label: "Blog Posts",
    group: "course",
    icon: Newspaper,
    hasStatus: false,
    formFields: [
      { key: "title", label: "Title", type: "text", required: true },
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "excerpt", label: "Excerpt", type: "textarea" },
      { key: "content", label: "Content", type: "textarea" },
      { key: "category", label: "Category", type: "text" },
      { key: "readTime", label: "Read Time (minutes)", type: "number" },
      { key: "publishedDate", label: "Published Date", type: "text" },
      { key: "coverImage", label: "Cover Image URL", type: "text" },
      { key: "authorName", label: "Author Name", type: "text" },
      { key: "tags", label: "Tags (comma separated)", type: "stringList" },
      { key: "ctaButton.label", label: "CTA Button Label", type: "text" },
      { key: "ctaButton.url", label: "CTA Button URL", type: "text" },
      { key: "ctaButton.isVisible", label: "CTA Button Visible", type: "boolean" },
      { key: "status", label: "Status (draft/published)", type: "text" },
      { key: "isVisible", label: "Visible", type: "boolean" },
    ],
  },
];

export function getModuleBySlug(slug: string): CmsModuleConfig | undefined {
  const all = [
    HOME_CMS_MODULE,
    HOME_SECTIONS_MODULE,
    ...CMS_MODULES,
  ];
  return all.find((m) => m.slug === slug);
}
