import type { FormField } from "@/app/frontend/CMS/config/cms-field-types";

export const HOME_API_PATH = "/home";
export const HOME_SECTIONS_API_PATH = "/home_sections";

export const HOME_CMS_FORM_FIELDS: FormField[] = [
  { key: "heroBadgeText", label: "Hero Badge Text", type: "text" },
  { key: "heroTitle", label: "Hero Title", type: "text" },
  { key: "heroSubtitle", label: "Hero Subtitle", type: "textarea" },
  { key: "heroBrandMark", label: "Hero Brand Mark", type: "text" },
  { key: "heroVerseArabic", label: "Hero Verse Arabic", type: "textarea" },
  { key: "heroVerseTranslation", label: "Hero Verse Translation", type: "textarea" },
  {
    key: "heroPrimaryButton.label",
    label: "Hero Primary Button Label",
    type: "text",
    rowGroup: "hero-primary-button",
  },
  {
    key: "heroPrimaryButton.url",
    label: "Hero Primary Button URL",
    type: "text",
    rowGroup: "hero-primary-button",
  },
  {
    key: "heroPrimaryButton.style",
    label: "Hero Primary Button Style",
    type: "text",
    rowGroup: "hero-primary-button",
  },
  {
    key: "heroPrimaryButton.isVisible",
    label: "Hero Primary Button Visible",
    type: "boolean",
    rowGroup: "hero-primary-button",
  },
  {
    key: "heroSecondaryButton.label",
    label: "Hero Secondary Button Label",
    type: "text",
    rowGroup: "hero-secondary-button",
  },
  {
    key: "heroSecondaryButton.url",
    label: "Hero Secondary Button URL",
    type: "text",
    rowGroup: "hero-secondary-button",
  },
  {
    key: "heroSecondaryButton.style",
    label: "Hero Secondary Button Style",
    type: "text",
    rowGroup: "hero-secondary-button",
  },
  {
    key: "heroSecondaryButton.isVisible",
    label: "Hero Secondary Button Visible",
    type: "boolean",
    rowGroup: "hero-secondary-button",
  },
  {
    key: "heroLearnerCountText",
    label: "Hero Learner Count Text",
    type: "text",
    rowGroup: "hero-learner-row",
    rowColumns: 2,
  },
  {
    key: "heroIsVisible",
    label: "Hero Visible",
    type: "boolean",
    rowGroup: "hero-learner-row",
  },
  { key: "stats", label: "Stats", type: "statsList" },
  { key: "statsIsVisible", label: "Stats Visible", type: "boolean" },
];

export const HOME_SECTIONS_FORM_FIELDS: FormField[] = [
  {
    key: "fieldSection.eyebrow",
    label: "Eyebrow",
    type: "text",
    rowGroup: "field-section-header",
    rowColumns: 3,
  },
  {
    key: "fieldSection.title",
    label: "Title",
    type: "text",
    rowGroup: "field-section-header",
    rowColumns: 3,
  },
  {
    key: "fieldSection.cardNumberVisible",
    label: "Cards to Show",
    type: "text",
    rowGroup: "field-section-header",
    rowColumns: 3,
  },
  {
    key: "fieldSection.subtitle",
    label: "Subtitle",
    type: "textarea",
  },
  { key: "fieldSection.isVisible", label: "Section Visible", type: "boolean" },
  {
    key: "featuredCoursesSection.eyebrow",
    label: "Eyebrow",
    type: "text",
    rowGroup: "featured-section-header",
    rowColumns: 3,
  },
  {
    key: "featuredCoursesSection.title",
    label: "Title",
    type: "text",
    rowGroup: "featured-section-header",
    rowColumns: 3,
  },
  {
    key: "featuredCoursesSection.cardNumberVisible",
    label: "Cards to Show",
    type: "text",
    rowGroup: "featured-section-header",
    rowColumns: 3,
  },
  {
    key: "featuredCoursesSection.subtitle",
    label: "Subtitle",
    type: "textarea",
  },
  { key: "featuredCoursesSection.isVisible", label: "Section Visible", type: "boolean" },
  {
    key: "featuredCoursesSection.viewAllButton.text",
    label: "View All Button Text",
    type: "text",
    rowGroup: "featured-view-all-button",
  },
  {
    key: "featuredCoursesSection.viewAllButton.url",
    label: "View All Button URL",
    type: "text",
    rowGroup: "featured-view-all-button",
  },
  {
    key: "featuredCoursesSection.viewAllButton.isVisible",
    label: "View All Button Visible",
    type: "boolean",
    rowGroup: "featured-view-all-button",
  },
  {
    key: "whyYaclamSection.eyebrow",
    label: "Eyebrow",
    type: "text",
    rowGroup: "why-yaclam-section-header",
    rowColumns: 3,
  },
  {
    key: "whyYaclamSection.title",
    label: "Title",
    type: "text",
    rowGroup: "why-yaclam-section-header",
    rowColumns: 3,
  },
  {
    key: "whyYaclamSection.cardNumberVisible",
    label: "Cards to Show",
    type: "text",
    rowGroup: "why-yaclam-section-header",
    rowColumns: 3,
  },
  {
    key: "whyYaclamSection.subtitle",
    label: "Subtitle",
    type: "textarea",
  },
  { key: "whyYaclamSection.isVisible", label: "Section Visible", type: "boolean" },
  {
    key: "roadmapsSection.eyebrow",
    label: "Eyebrow",
    type: "text",
    rowGroup: "roadmaps-section-header",
    rowColumns: 3,
  },
  {
    key: "roadmapsSection.title",
    label: "Title",
    type: "text",
    rowGroup: "roadmaps-section-header",
    rowColumns: 3,
  },
  {
    key: "roadmapsSection.cardNumberVisible",
    label: "Cards to Show",
    type: "text",
    rowGroup: "roadmaps-section-header",
    rowColumns: 3,
  },
  {
    key: "roadmapsSection.subtitle",
    label: "Subtitle",
    type: "textarea",
  },
  { key: "roadmapsSection.isVisible", label: "Section Visible", type: "boolean" },
  {
    key: "roadmapsSection.allRoadmapsButton.text",
    label: "All Roadmaps Button Text",
    type: "text",
    rowGroup: "roadmaps-all-button",
  },
  {
    key: "roadmapsSection.allRoadmapsButton.url",
    label: "All Roadmaps Button URL",
    type: "text",
    rowGroup: "roadmaps-all-button",
  },
  {
    key: "roadmapsSection.allRoadmapsButton.isVisible",
    label: "All Roadmaps Button Visible",
    type: "boolean",
    rowGroup: "roadmaps-all-button",
  },
  {
    key: "scholarshipsSection.eyebrow",
    label: "Eyebrow",
    type: "text",
    rowGroup: "scholarships-section-header",
    rowColumns: 3,
  },
  {
    key: "scholarshipsSection.title",
    label: "Title",
    type: "text",
    rowGroup: "scholarships-section-header",
    rowColumns: 3,
  },
  {
    key: "scholarshipsSection.cardNumberVisible",
    label: "Cards to Show",
    type: "text",
    rowGroup: "scholarships-section-header",
    rowColumns: 3,
  },
  {
    key: "scholarshipsSection.subtitle",
    label: "Subtitle",
    type: "textarea",
  },
  { key: "scholarshipsSection.isVisible", label: "Section Visible", type: "boolean" },
  {
    key: "scholarshipsSection.browseAllButton.text",
    label: "Browse All Button Text",
    type: "text",
    rowGroup: "scholarships-browse-all-button",
  },
  {
    key: "scholarshipsSection.browseAllButton.url",
    label: "Browse All Button URL",
    type: "text",
    rowGroup: "scholarships-browse-all-button",
  },
  {
    key: "scholarshipsSection.browseAllButton.isVisible",
    label: "Browse All Button Visible",
    type: "boolean",
    rowGroup: "scholarships-browse-all-button",
  },
  {
    key: "practitionersSection.eyebrow",
    label: "Eyebrow",
    type: "text",
    rowGroup: "practitioners-section-header",
    rowColumns: 3,
  },
  {
    key: "practitionersSection.title",
    label: "Title",
    type: "text",
    rowGroup: "practitioners-section-header",
    rowColumns: 3,
  },
  {
    key: "practitionersSection.cardNumberVisible",
    label: "Cards to Show",
    type: "text",
    rowGroup: "practitioners-section-header",
    rowColumns: 3,
  },
  {
    key: "practitionersSection.subtitle",
    label: "Subtitle",
    type: "textarea",
  },
  { key: "practitionersSection.isVisible", label: "Section Visible", type: "boolean" },
  {
    key: "testimonialsSection.eyebrow",
    label: "Eyebrow",
    type: "text",
    rowGroup: "testimonials-section-header",
    rowColumns: 3,
  },
  {
    key: "testimonialsSection.title",
    label: "Title",
    type: "text",
    rowGroup: "testimonials-section-header",
    rowColumns: 3,
  },
  {
    key: "testimonialsSection.cardNumberVisible",
    label: "Cards to Show",
    type: "text",
    rowGroup: "testimonials-section-header",
    rowColumns: 3,
  },
  {
    key: "testimonialsSection.subtitle",
    label: "Subtitle",
    type: "textarea",
  },
  { key: "testimonialsSection.isVisible", label: "Section Visible", type: "boolean" },
  { key: "ctaSection.title", label: "Title", type: "text" },
  { key: "ctaSection.subtitle", label: "Subtitle", type: "textarea" },
  {
    key: "ctaSection.primaryButton.text",
    label: "Primary Button Text",
    type: "text",
    rowGroup: "cta-primary-button",
  },
  {
    key: "ctaSection.primaryButton.url",
    label: "Primary Button URL",
    type: "text",
    rowGroup: "cta-primary-button",
  },
  {
    key: "ctaSection.primaryButton.isVisible",
    label: "Primary Button Visible",
    type: "boolean",
    rowGroup: "cta-primary-button",
  },
  {
    key: "ctaSection.secondaryButton.text",
    label: "Secondary Button Text",
    type: "text",
    rowGroup: "cta-secondary-button",
  },
  {
    key: "ctaSection.secondaryButton.url",
    label: "Secondary Button URL",
    type: "text",
    rowGroup: "cta-secondary-button",
  },
  {
    key: "ctaSection.secondaryButton.isVisible",
    label: "Secondary Button Visible",
    type: "boolean",
    rowGroup: "cta-secondary-button",
  },
  { key: "ctaSection.isVisible", label: "CTA Section Visible", type: "boolean" },
];

/** Defaults for POST /home_sections/create (matches API document shape). */
export const HOME_SECTIONS_FORM_DEFAULTS: Record<string, unknown> = {
  "fieldSection.eyebrow": "Browse",
  "fieldSection.title": "Find your field",
  "fieldSection.subtitle":
    "Explore practical, job-ready skills across the disciplines that matter most.",
  "fieldSection.cardNumberVisible": "5",
  "fieldSection.isVisible": true,
  "featuredCoursesSection.eyebrow": "Popular",
  "featuredCoursesSection.title": "Featured courses",
  "featuredCoursesSection.subtitle":
    "Hand-picked, top-rated programmes loved by thousands of learners.",
  "featuredCoursesSection.cardNumberVisible": "5",
  "featuredCoursesSection.isVisible": true,
  "featuredCoursesSection.viewAllButton.text": "View all",
  "featuredCoursesSection.viewAllButton.url": "/courses",
  "featuredCoursesSection.viewAllButton.isVisible": true,
  "whyYaclamSection.eyebrow": "Why Yaclam",
  "whyYaclamSection.title": "Education built for you",
  "whyYaclamSection.subtitle":
    "Everything you need to learn, get certified and move your career forward.",
  "whyYaclamSection.cardNumberVisible": "5",
  "whyYaclamSection.isVisible": true,
  "roadmapsSection.eyebrow": "Career Roadmaps",
  "roadmapsSection.title": "Your path to a career",
  "roadmapsSection.subtitle":
    "Salary data, in-demand skills and a guided learning sequence for every role.",
  "roadmapsSection.cardNumberVisible": "5",
  "roadmapsSection.isVisible": true,
  "roadmapsSection.allRoadmapsButton.text": "All roadmaps",
  "roadmapsSection.allRoadmapsButton.url": "/roadmaps",
  "roadmapsSection.allRoadmapsButton.isVisible": true,
  "scholarshipsSection.eyebrow": "Funded Futures",
  "scholarshipsSection.title": "Scholarships database",
  "scholarshipsSection.subtitle":
    "Fully and partially funded opportunities, updated and explained — apply with confidence.",
  "scholarshipsSection.cardNumberVisible": "5",
  "scholarshipsSection.isVisible": true,
  "scholarshipsSection.browseAllButton.text": "Browse all",
  "scholarshipsSection.browseAllButton.url": "/scholarships",
  "scholarshipsSection.browseAllButton.isVisible": true,
  "practitionersSection.eyebrow": "Expert-led",
  "practitionersSection.title": "Learn from practitioners",
  "practitionersSection.subtitle":
    "Our instructors teach what they actually do — no theory without practice.",
  "practitionersSection.cardNumberVisible": "5",
  "practitionersSection.isVisible": true,
  "testimonialsSection.eyebrow": "Learners",
  "testimonialsSection.title": "Real outcomes",
  "testimonialsSection.subtitle":
    "From first lesson to first job offer — here is what learners say.",
  "testimonialsSection.cardNumberVisible": "5",
  "testimonialsSection.isVisible": true,
  "ctaSection.title": "Your future is one decision away",
  "ctaSection.subtitle":
    "Join thousands of Somali learners building skills, earning certificates and changing their lives. Start free today.",
  "ctaSection.primaryButton.text": "Create free account",
  "ctaSection.primaryButton.url": "/register",
  "ctaSection.primaryButton.isVisible": true,
  "ctaSection.secondaryButton.text": "Browse courses",
  "ctaSection.secondaryButton.url": "/courses",
  "ctaSection.secondaryButton.isVisible": true,
  "ctaSection.isVisible": true,
};
